% -------------------------------------------------------------------
%  Generated by MATLAB on 1-Jan-2025 19:21:10
%  MATLAB version: 24.2.0.2712019 (R2024b)
% -------------------------------------------------------------------
saveVarsMat = load('RootLocus.mat');

ans = 2;

s = saveVarsMat.s; % <1x1 tf> unsupported class

sys = saveVarsMat.sys; % <1x1 tf> unsupported class

wn = 2;

zeta = 0.7;

clear saveVarsMat;
